### ISSUE TITLE
Include guidelines for contributing

### ISSUE THREAD

**Issue by darwinyip** [nysenate/NYSenate.gov-Website-D9#149]
Please include CONTRIBUTING.md

**Comment by routinet** [comment]
@darwinyip Hello!  First and foremost, thanks for participating!

We do not have any hard-and-fast guidelines for how contributions should be made, but we're happy to look at creating some.  GrumPHP generates a pre-commit hook when `composer install` is run, so that will help commits comply with our syntax and style rules.  Generally speaking, we're following Drupal's rules, and plan to implement the "best practices" rule-set in the near future.  Any other vetting of submissions is done by our internal team as the need arises.  So far, we've only had one PR submission from outside our organization, and it ended up being absorbed into one our internal PRs out of convenience.  

That said, if you'd like to contribute a CONTRIBUTING.md, that would be a great start.  😄
